# Generated by Django 4.0.3 on 2022-03-30 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='member_type',
            new_name='post_type',
        ),
    ]
