# Generated by Django 4.0.3 on 2022-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='title',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
