# Generated by Django 4.0.3 on 2022-04-16 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teamfollowrelation_follower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_type',
            field=models.CharField(choices=[('Co', 'Confirmed'), ('PE', 'Pended')], default='Co', max_length=2),
        ),
    ]
