# Generated by Django 4.0.3 on 2022-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_teamprofile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamprofile',
            name='background_image',
            field=models.URLField(blank=True, default='', max_length=511),
        ),
        migrations.AlterField(
            model_name='teamprofile',
            name='team_profile_image',
            field=models.URLField(blank=True, default='', max_length=511),
        ),
    ]
