# Generated by Django 4.0.3 on 2022-04-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_background_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('미술/디자인', 'Art'), ('음악/작곡', 'Music'), ('영상/미디어', 'Media'), ('무용/연극', 'Show')], default='미술/디자인', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('순수예술', 'Fine'), ('조소/조각', 'Ridicule'), ('공예', 'Craft'), ('일러스트', 'Illustration'), ('산업디자인', 'Industrial Design'), ('건축', 'Construct'), ('전통예술', 'Traditional Art'), ('클래식', 'Classic'), ('피아노', 'Piano'), ('밴드', 'Band'), ('작사/작곡', 'Composition'), ('전통음악', 'Traditional Music'), ('K-POP', 'K Pop'), ('모션그래픽', 'Motion Graphic'), ('pd', 'Pd'), ('movie', 'Movie'), ('animation', 'Animation'), ('3D아트', 'Three D'), ('게임그래픽', 'Game Graphic'), ('사진', 'Picture'), ('공연기획', 'Performance'), ('현대무용', 'Modern Dance'), ('연기', 'Acting'), ('각본/각색', 'Scenario')], default='순수예술', max_length=15)),
                ('main', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.maincategory')),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='user',
            name='categories',
            field=models.ManyToManyField(to='accounts.subcategory'),
        ),
    ]
