# Generated by Django 4.0.3 on 2022-04-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_maincategory_subcategory_delete_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategory', to='accounts.maincategory'),
        ),
    ]
