# Generated by Django 4.0.3 on 2022-06-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_image',
            field=models.URLField(blank=True, default='', max_length=511),
        ),
    ]
